# Generated by Django 5.1 on 2024-10-01 08:40

import django.core.validators
import django.db.models.deletion
import flightdesk.models
import flightdesk.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(default=flightdesk.models.generate_mybooking_id, editable=False, max_length=20, unique=True)),
                ('currency', models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=3)),
                ('mco', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('authorizing', 'Authorizing'), ('allocating', 'Allocating'), ('confirmed', 'Confirmed'), ('cleared', 'Cleared')], default='initiated', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regarding_flight', models.BooleanField(default=False)),
                ('regarding_hotel', models.BooleanField(default=False)),
                ('regarding_vehicle', models.BooleanField(default=False)),
                ('subcategory', models.CharField(blank=True, max_length=255)),
                ('flight_cost', models.FloatField(default=0)),
                ('hotel_cost', models.FloatField(default=0)),
                ('vehicle_cost', models.FloatField(default=0)),
                ('flight_info_img', models.ImageField(blank=True, null=True, upload_to='booking/flight_info/')),
                ('hotel_info_img', models.ImageField(blank=True, null=True, upload_to='booking/hotel_info/')),
                ('vehicle_info_img', models.ImageField(blank=True, null=True, upload_to='booking/vehicle_info/')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('AmericanExpress', 'American Express')], default='Visa', max_length=20)),
                ('card_holder_name', models.CharField(default=None, max_length=255)),
                ('card_holder_number', models.CharField(default=None, max_length=20)),
                ('email', models.EmailField(default=None, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Enter a valid 16-digit card number.')])),
                ('expiry_date', models.CharField(max_length=5, validators=[flightdesk.validators.CardExpiryValidator()])),
                ('card_cvv', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3,4}$', 'Enter a valid CVV.')])),
                ('primary_address', models.TextField(default=None)),
                ('country', models.CharField(default=None, max_length=100)),
                ('zipcode', models.CharField(default=None, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{5}(-\\d{4})?$', 'Enter a valid ZIP code.')])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightdesk.booking')),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('converted', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('call_date', models.DateTimeField(auto_now_add=True)),
                ('concern', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flightdesk.campaign')),
                ('query_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flightdesk.query')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='call_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flightdesk.calllog'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('recipient', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('booking', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightdesk.booking')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachtment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(blank=True, upload_to='email_attachments')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightdesk.email')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_passenger_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('ticket_number', models.CharField(blank=True, max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightdesk.booking')),
            ],
        ),
    ]
