# Generated by Django 4.2.6 on 2023-12-22 07:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import flightdesk.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(blank=True, max_length=255, null=True)),
                ('airline_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gds_pnr', models.CharField(blank=True, default=None, max_length=50)),
                ('confirmation_arl', models.CharField(blank=True, default=None, max_length=50)),
                ('booking_id', models.CharField(default=flightdesk.models.generate_booking_id, max_length=8, unique=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('CAD', 'CAD')], default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('authorizing', 'Authorizing'), ('allocating', 'Allocating'), ('confirmed', 'Confirmed')], default='initiated', max_length=20)),
                ('agent_remarks', models.TextField(blank=True, default=str)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(default=flightdesk.models.generate_booking_id, max_length=8, unique=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('CAD', 'CAD')], default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='requested', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_passenger_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('ticket_number', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightdesk.booking')),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('call_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Booking', 'Booking'), ('Refund', 'Refund'), ('FutureCredit', 'Future Credit'), ('Other', 'Other')], default='Booking', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flightdesk.booking')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flightdesk.refund')),
            ],
        ),
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('AmericanExpress', 'American Express')], default='Visa', max_length=20)),
                ('card_holder_name', models.CharField(default=None, max_length=255)),
                ('card_number', models.CharField(default=None, max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Enter a valid 16-digit card number.')])),
                ('expiry_date', models.CharField(default=None, max_length=5, validators=[flightdesk.models.CardExpiryValidator()])),
                ('card_cvv', models.CharField(default=None, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3,4}$', 'Enter a valid CVV.')])),
                ('gateway_source', models.CharField(default=None, max_length=255)),
                ('billing_address', models.TextField(default=None)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightdesk.booking')),
            ],
        ),
    ]
