# Generated by Django 5.0.1 on 2024-01-10 20:57

import django.core.validators
import django.db.models.deletion
import flightdesk.models
import flightdesk.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FutureCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_credit_id', models.CharField(default=flightdesk.models.generate_mybooking_id, max_length=8, unique=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('CAD', 'CAD')], default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='requested', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(default=flightdesk.models.generate_mybooking_id, max_length=8, unique=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('CAD', 'CAD')], default='USD', max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='requested', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('call_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('MyBooking', 'MyBooking'), ('Refund', 'Refund'), ('FutureCredit', 'Future Credit'), ('Other', 'Other')], default='MyBooking', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='MyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mybooking_id', models.CharField(default=flightdesk.models.generate_mybooking_id, max_length=8, unique=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('CAD', 'CAD')], default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('authorizing', 'Authorizing'), ('allocating', 'Allocating'), ('confirmed', 'Confirmed')], default='initiated', max_length=20)),
                ('mco', models.CharField(choices=[('Waiting', 'waiting'), ('cleared', 'Cleared'), ('failed', 'Failed'), ('Refunded', 'refunded')], default='initiated', max_length=20)),
                ('agent_remarks', models.TextField(blank=True, default=str)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(blank=True, max_length=255, null=True)),
                ('airline_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('CAD', 'CAD')], default='USD', max_length=3)),
                ('gds_pnr', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('from_location', models.CharField(blank=True, max_length=255, null=True)),
                ('to_location', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_datetime', models.DateTimeField(blank=True, null=True)),
                ('arrival_datetime', models.DateTimeField(blank=True, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=10, null=True)),
                ('mybooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_details', to='flightdesk.mybooking')),
            ],
        ),
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('AmericanExpress', 'American Express')], default='Visa', max_length=20)),
                ('card_holder_name', models.CharField(default=None, max_length=255)),
                ('card_number', models.CharField(default=None, max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Enter a valid 16-digit card number.')])),
                ('expiry_date', models.CharField(default=None, max_length=5, validators=[flightdesk.validators.CardExpiryValidator()])),
                ('card_cvv', models.CharField(default=None, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3,4}$', 'Enter a valid CVV.')])),
                ('gateway_source', models.CharField(default=None, max_length=255)),
                ('billing_address', models.TextField(default=None)),
                ('mybooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightdesk.mybooking')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_passenger_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('ticket_number', models.CharField(max_length=50)),
                ('mybooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightdesk.mybooking')),
            ],
        ),
    ]
