# Generated by Django 5.0.2 on 2024-02-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybooking',
            name='mco',
        ),
        migrations.AlterField(
            model_name='calllog',
            name='category',
            field=models.CharField(choices=[('New Booking', 'New Booking'), ('Cancelation', 'Cancelation'), ('Other', 'Other')], default='MyBooking', max_length=20),
        ),
    ]
