# Generated by Django 4.2.6 on 2023-12-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('flightdesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='refund',
        ),
        migrations.AddField(
            model_name='calllog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
