# Generated by Django 5.0.1 on 2024-01-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='mco',
            field=models.CharField(choices=[('Waiting', 'waiting'), ('Cleared', 'cleared'), ('failed', 'Failed'), ('Refunded', 'refunded')], default='initiated', max_length=20),
        ),
    ]
