# Generated by Django 5.1 on 2024-10-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0002_rename_airline_calllog_airline_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calllog',
            old_name='airline_id',
            new_name='airline',
        ),
    ]
