# Generated by Django 4.2.6 on 2023-12-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0002_remove_calllog_booking_remove_calllog_refund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='confirmation_arl',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gds_pnr',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
