# Generated by Django 5.0.1 on 2024-01-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0002_alter_bid_mco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='mco',
            field=models.CharField(choices=[('Waiting', 'waiting'), ('Cleared', 'cleared'), ('Failed', 'failed'), ('refunded', 'Refunded')], default='initiated', max_length=20),
        ),
    ]
