# Generated by Django 5.0.2 on 2024-02-12 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0002_remove_mybooking_mco_alter_calllog_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyBooking',
            new_name='Booking',
        ),
        migrations.RenameField(
            model_name='billinginformation',
            old_name='mybooking',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='flightdetails',
            old_name='mybooking',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='mybooking',
            new_name='booking',
        ),
        migrations.AlterField(
            model_name='calllog',
            name='category',
            field=models.CharField(choices=[('New Booking', 'New Booking'), ('Cancelation', 'Cancelation'), ('Other', 'Other')], default='Booking', max_length=20),
        ),
    ]
