# Generated by Django 5.0.1 on 2024-01-11 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0002_alter_calllog_email_alter_mybooking_mco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetails',
            name='mybooking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightdesk.mybooking'),
        ),
        migrations.AlterField(
            model_name='mybooking',
            name='mco',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('cleared', 'Cleared'), ('failed', 'Failed'), ('Refunded', 'refunded')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mybooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightdesk.mybooking')),
            ],
        ),
    ]
