# Generated by Django 5.0.1 on 2024-01-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0003_alter_flightdetails_mybooking_alter_mybooking_mco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooking',
            name='boarding_pass',
            field=models.ImageField(blank=True, upload_to='boarding_passes'),
        ),
        migrations.AddField(
            model_name='mybooking',
            name='e_ticket',
            field=models.ImageField(blank=True, upload_to='e_tickets'),
        ),
        migrations.AlterField(
            model_name='emailattachtment',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='email_attachments'),
        ),
        migrations.AlterField(
            model_name='mybooking',
            name='mco',
            field=models.CharField(choices=[('Waiting', 'waiting'), ('Cleared', 'cleared'), ('Failed', 'failed')], default='initiated', max_length=20),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
