# Generated by Django 5.1 on 2024-10-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0003_rename_airline_id_calllog_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
