# Generated by Django 5.0.2 on 2024-02-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0003_rename_mybooking_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('booking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flightdesk.booking')),
                ('reason', models.CharField(choices=[('Schedule change', 'Schedule change'), ('Personal reason', 'Personal reason'), ('Price too high', 'Price too high'), ('Other', 'Other')], max_length=100)),
                ('cancellation_number', models.CharField(max_length=20, unique=True)),
            ],
            bases=('flightdesk.booking',),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='boarding_pass',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='e_ticket',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='mybooking_id',
            new_name='booking_id',
        ),
        migrations.CreateModel(
            name='NewBooking',
            fields=[
                ('booking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flightdesk.booking')),
                ('e_ticket', models.ImageField(blank=True, upload_to='e_tickets')),
                ('boarding_pass', models.ImageField(blank=True, upload_to='boarding_passes')),
            ],
            bases=('flightdesk.booking',),
        ),
    ]
