# Generated by Django 5.1 on 2025-01-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0004_privatechat_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionCategorySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
