# Generated by Django 5.0.1 on 2024-01-04 00:13

import flightdesk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0004_alter_booking_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_credit_id', models.CharField(default=flightdesk.models.generate_booking_id, max_length=8, unique=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('CAD', 'CAD')], default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='requested', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_image',
            field=models.ImageField(blank=True, null=True, upload_to='booking_ticket_images/'),
        ),
    ]
