# Generated by Django 5.0.2 on 2024-02-12 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0004_cancellation_remove_booking_boarding_pass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('booking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flightdesk.booking')),
                ('category', models.CharField(choices=[('Baggage', 'Baggage'), ('Meal', 'Meal'), ('Pet', 'Pet')], max_length=100)),
                ('pnr', models.CharField(max_length=20, unique=True)),
            ],
            bases=('flightdesk.booking',),
        ),
        migrations.DeleteModel(
            name='FutureCredit',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.RenameField(
            model_name='cancellation',
            old_name='cancellation_number',
            new_name='pnr',
        ),
        migrations.AlterField(
            model_name='calllog',
            name='category',
            field=models.CharField(choices=[('New Booking', 'New Booking'), ('Cancelation', 'Cancelation'), ('Addition', 'Addition'), ('Other', 'Other')], default='Booking', max_length=20),
        ),
    ]
