# Generated by Django 5.0.1 on 2024-01-11 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0004_mybooking_boarding_pass_mybooking_e_ticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='added_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mybooking',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('authorizing', 'Authorizing'), ('allocating', 'Allocating'), ('confirmed', 'Confirmed'), ('cleared', 'Cleared')], default='initiated', max_length=20),
        ),
    ]
