# Generated by Django 5.0.2 on 2024-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0005_addition_delete_futurecredit_delete_refund_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pet_type', models.CharField(default='None', max_length=10)),
                ('no_of_meals', models.CharField(default=0, max_length=1)),
            ],
        ),
    ]
