# Generated by Django 5.0.1 on 2024-01-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0005_futurecredit_booking_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Waiting', 'waiting'), ('Cleared', 'cleared'), ('Failed', 'failed'), ('refunded', 'Refunded')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('authorizing', 'Authorizing'), ('allocating', 'Allocating'), ('confirmed', 'Confirmed')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
    ]
