# Generated by Django 5.1 on 2025-02-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0006_alter_revision_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginformation',
            name='staff_fill_billing',
            field=models.BooleanField(default=True),
        ),
    ]
