# Generated by Django 5.1 on 2024-08-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0006_addinline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calllog',
            old_name='remark',
            new_name='concern',
        ),
        migrations.RenameField(
            model_name='calllog',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='object_id',
        ),
        migrations.AddField(
            model_name='calllog',
            name='converted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
        ),
        migrations.AddField(
            model_name='calllog',
            name='tag',
            field=models.CharField(choices=[('LMF', 'LMF'), ('877', '877'), ('TOH', 'TOH'), ('Other', 'Other')], default='Booking', max_length=20),
        ),
    ]
