# Generated by Django 5.0.1 on 2024-01-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0006_alter_bid_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='mco',
            field=models.CharField(choices=[('Waiting', 'waiting'), ('Cleared', 'cleared'), ('failed', 'Failed'), ('Refunded', 'refunded')], default='initiated', max_length=20),
        ),
        migrations.CreateModel(
            name='BIDPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightdesk.bid')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightdesk.passenger')),
            ],
        ),
    ]
