# Generated by Django 5.1 on 2024-08-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0007_rename_remark_calllog_concern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='tag',
            field=models.CharField(choices=[('LMF', 'LMF'), ('877', '877'), ('TOH', 'TOH'), ('Other', 'Other')], default='LMF', max_length=20),
        ),
    ]
