# Generated by Django 5.1 on 2025-02-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0007_billinginformation_staff_fill_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginformation',
            name='staff_fill_billing',
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_fill_billing',
            field=models.BooleanField(default=True),
        ),
    ]
