# Generated by Django 5.1 on 2025-02-22 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0008_remove_billinginformation_staff_fill_billing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Total budget allocated', max_digits=10)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount spent so far', max_digits=10)),
                ('traffic', models.IntegerField(default=0, help_text='Total traffic generated')),
                ('conversions', models.IntegerField(default=0, help_text='Successful conversions from the campaign')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
