# Generated by Django 5.1 on 2024-08-31 12:26

import django.core.validators
import django.db.models.deletion
import flightdesk.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0009_campaign_alter_calllog_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddInline',
        ),
        migrations.RemoveField(
            model_name='cancellation',
            name='booking_ptr',
        ),
        migrations.RemoveField(
            model_name='flightdetails',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='booking_ptr',
        ),
        migrations.RemoveField(
            model_name='billinginformation',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='billinginformation',
            name='gateway_source',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='agent_remarks',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='card_holder_number',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='email',
            field=models.EmailField(default=None, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='primary_address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='zipcode',
            field=models.CharField(default=None, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{5}(-\\d{4})?$', 'Enter a valid ZIP code.')]),
        ),
        migrations.AddField(
            model_name='booking',
            name='call_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flightdesk.calllog'),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_info_img',
            field=models.ImageField(blank=True, null=True, upload_to='booking/flight_info/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_info_img',
            field=models.ImageField(blank=True, null=True, upload_to='booking/hotel_info/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='mco',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='regarding_flight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='regarding_hotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='regarding_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_info_img',
            field=models.ImageField(blank=True, null=True, upload_to='booking/vehicle_info/'),
        ),
        migrations.AlterField(
            model_name='billinginformation',
            name='card_holder_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=flightdesk.models.generate_mybooking_id, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('authorizing', 'Authorizing'), ('allocating', 'Allocating'), ('confirmed', 'Confirmed'), ('cleared', 'Cleared')], default='initiated', max_length=15),
        ),
        migrations.DeleteModel(
            name='Addition',
        ),
        migrations.DeleteModel(
            name='Cancellation',
        ),
        migrations.DeleteModel(
            name='FlightDetails',
        ),
        migrations.DeleteModel(
            name='NewBooking',
        ),
    ]
