# Generated by Django 5.1 on 2025-03-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0010_alter_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
