# Generated by Django 5.1 on 2024-09-02 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0010_delete_addinline_remove_cancellation_booking_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='added_by',
        ),
        migrations.AddField(
            model_name='email',
            name='booking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightdesk.booking'),
        ),
    ]
