# Generated by Django 5.1 on 2025-03-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0011_alter_booking_mco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flight_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
