# Generated by Django 5.1 on 2024-09-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightdesk', '0012_query_calllog_query_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='flight_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mco',
            field=models.FloatField(default=0),
        ),
    ]
